---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: spring-pet-clinic
  namespace: accelerator-system
spec:
  git:
    ref:
      branch: accelerator
    url: https://github.com/jlafata/spring-petclinic.git
#    interval: 10s
