apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic
    apps.tanzu.vmware.com/has-tests: "true"
#    catalog_disposition: to_be_collect
spec:
  source:
    git:
      url: https://github.com/jlafata/spring-petclinic.git
      ref:
        branch: accelerator

